language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - npm test
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE wayfarer;' -U postgres
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"